# -*- coding: utf-8 -*-
"""Q1_huggingface.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zGRPIB8TIs-qSQAWzV7cx5u7D101WFbt
"""

!pip install transformers tokenization_auto

from transformers import pipeline

from transformers import DistilBertForMaskedLM

QA = pipeline('question-answering', model='distilbert-base-cased-distilled-squad')

context = """
Somalia has a tropical climate, characterized by hot temperatures and seasonal rainfall.
The weather today in Mogadishu is sunny with a high of 32°C and a low of 26°C.
"""

question = "What is the weather of Somalia today?"

response = QA(question=question, context=context)
print(response['answer'])

